In [ ]:
import pandas as pd 

#data load
def load_data(file_path):
    try:
        df = pd.read_csv(file_path, encoding='latin1')
        print(f"File {file_path} loaded correctly using latin1 encoding. Loaded {len(df)} rows.")
        return df
    except Exception:
        df = pd.read_csv(file_path, encoding='cp1252')
        print(f"File {file_path} loaded correctly using cp1252 encoding. Loaded {len(df)} rows.")
        return df
    
df_oms = load_data('oms_orders_placed.csv')
df_wms = load_data('wms_shipped_units.csv')

File oms_orders_placed.csv loaded correctly using latin1 encoding. Loaded 541909 rows.
File wms_shipped_units.csv loaded correctly using latin1 encoding. Loaded 542409 rows.

In [15]:
print("OMS Preview:")
display(df_oms.head(5))

print("WMS Preview:")
display(df_wms.head(5))

OMS Preview:

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

WMS Preview:

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,ERR_DATE_2024,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,ERR_DATE_2024,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,ERR_DATE_2024,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,ERR_DATE_2024,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,ERR_DATE_2024,3.39,17850.0,United Kingdom

In [ ]:
# dataset shape check
print(f"OMS (Orders Placed) rows: {df_oms.shape[0]}, columns: {df_oms.shape[1]}")
print(f"WMS (Shipped Units) rows: {df_wms.shape[0]}, columns: {df_wms.shape[1]}")

if df_oms.shape[0] != df_wms.shape[0]:
    print(f" Discrepancy detected! Difference: {abs(df_oms.shape[0] - df_wms.shape[0])} records.")

OMS (Orders Placed) rows: 541909, columns: 8
WMS (Shipped Units) rows: 542409, columns: 8
 Discrepancy detected! Difference: 500 records.